spring.application.name=authify

spring.datasource.url= jdbc:mysql://localhost:3306/authify_db
spring.datasource.username=root
spring.datasource.password=Sachin#102912
spring.jpa.hibernate.ddl-auto=update