spring.application.name=ecom

#spring.h2.console.enabled=true
#spring.datasource.url=jdbc:h2:mem:test

#Database Connection
spring.datasource.url=jdbc:mysql://localhost:3306/ecom_db
spring.datasource.username=root
spring.datasource.password=Sachin#102912

#JPA
spring.jpa.hibernate.ddl-auto=update


